baseURL: "https://www.kastello.com.br"
languageCode: en-us
title: "kastello: Controle o seu reino de forma fácil e rápida"
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Seu castelo. Controlado.
    # Hero subtitle (optional)
    subtitle: Tenha sempre à mão as informações sobre a sua casa e tenha mais tempo para fazer o que te deixa feliz.
    subtitle2: Estamos em fase de desenvolvimento e integração com os orgãos públicos. Quer ser avisado quando estivermos prontos? Deixe seu email logo abaixo.
    # Button text
    buttontext: Cadastre-se agora
    # Where the main hero button links to
    buttonlink: "#contact"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - brcondos
    - casan
    - celesc
    - pmsj
    - pmf
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Produto
    url: /#product
  - title: Integrações
    url: /#contact
  - title: Preços
    url: /#contact
  - title: Blog
    url: /#contact
  - title: Pesquisa
    url: /pesquisa
  - title: Cadastrar
    url: /#contact
    button: true
  sidebar: 
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    # - title: User
    #   icon: user
    #   links:
    #   # - text: Profile
    #   #   url: /
    #   # - text: Account
    #   #   url: /
    #   # - text: Settings
    #   #   url: /
    # - title: Messages
    #   icon: envelope
    #   links:
    #   - text: Inbox
    #     url: /
    #   - text: Compose
    #     url: /
    # - title: Images
    #   icon: image
    #   links:
    #   - text: Library
    #     url: /
    #   - text: Upload
    #     url: /
    # - title: Settings
    #   icon: cog
    #   links:
    #   - text: User settings
    #     url: /
    #   - text: App settings
    #     url: /
  section1:
    title: Controle o seu lar
    subtitle: de forma simples e direta
    tiles:
    - title: Online
      icon: mouse-globe
      text: Nenhum sistema para instalar Tudo online. 24h
      url: /
      buttonText: Comece já
    - title: Segurança
      icon: laptop-cloud
      text: Seus dados estão seguros e bem guardados conosco
      url: /
      buttonText: Comece já
    - title: Integrações
      icon: plug-cloud
      text: Energia, prefeituras, gás e muito mais
      url: /
      buttonText: Comece já
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: kastello-logo-alt.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/kastello
      # Icons are from Font Awesome
      icon: github
    # - link: https://dribbble.com/#
    #   icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/kastello
      icon: twitter
    # - link: https://bitbucket.org/#
    #   icon: bitbucket
    bulmalogo: false
    product:
    - text: Conheça
      link: /
    - text: Preços
      link: /
    - text: Nosso roadmap
      link: /
    - text: Sugestões e ideias
      link: /
    docs:
    - text: Primeiros passos
      link: /
    - text: Manual de usuário
      link: /
    - text: Integrações
      link: /
    - text: API
      link: /
    blogroll:
    - text: Últimas notícias
      link: /
    - text: Engenharia
      link: /
    - text: Video blog
      link: /